# 
#  Dockerfile for GATE 7.0  
#  http://www.opengatecollaboration.org/
#
#  The image is based on the latest official Ubuntu (14.04) and on the latest official ROOT/Geant/Gate
#
#  
#

FROM dvolgyes/geant4
MAINTAINER David Völgyes <david.volgyes@ieee.org>

